# Generated by Django 2.2.9 on 2021-02-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hinnakiri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hinnakiri_lang',
            name='title',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
