# Generated by Django 2.2.9 on 2021-02-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hinnakiri', '0002_hinnakiri_lang_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hinnakiri_lang',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
