# Generated by Django 2.2.9 on 2021-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hinnakiri', '0003_hinnakiri_lang_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='hinnakiri_lang',
            name='pricing',
            field=models.TextField(blank=True),
        ),
    ]
