# Generated by Django 3.0 on 2021-02-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_lang',
            name='title',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
