# Generated by Django 3.0.2 on 2021-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_lang_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_lang',
            name='tagasi',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
