# Generated by Django 3.0.2 on 2021-02-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=999, unique=True)),
                ('phone', models.CharField(blank=True, max_length=999)),
                ('email', models.CharField(blank=True, max_length=999)),
                ('kirjeldus', models.TextField(blank=True)),
                ('lang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navbar.Lang')),
            ],
        ),
    ]
