# Generated by Django 3.0.2 on 2021-02-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
        ('treenerid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treenerid_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navbar.Lang')),
            ],
        ),
    ]
