# Generated by Django 3.0.2 on 2021-02-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treenerid', '0003_auto_20210202_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='treener',
            name='pilt',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
