# Generated by Django 2.2.9 on 2021-02-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treenerid', '0005_treenerid_lang_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenerid_lang',
            name='bg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
