# Generated by Django 2.2.9 on 2021-02-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_index_lang_bg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_lang',
            name='bg',
        ),
    ]
