# Generated by Django 3.0 on 2021-02-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutvustus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutvustus_lang',
            name='pilt',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tutvustus_lang',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
