# Generated by Django 3.0.2 on 2021-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0004_navbar_lang_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar_lang',
            name='footer_info',
            field=models.TextField(blank=True),
        ),
    ]
