# Generated by Django 3.0.2 on 2021-02-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_navbar_lang_footer_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toetaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=999)),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
