# Generated by Django 3.0.2 on 2021-02-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0006_toetaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='SEO_author',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='contact',
            name='SEO_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='SEO_tags',
            field=models.TextField(blank=True),
        ),
    ]
