# Generated by Django 2.2.9 on 2021-02-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(blank=True, max_length=999)),
                ('hind', models.FloatField(blank=True)),
                ('kirjeldus', models.TextField(blank=True)),
                ('lang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navbar.Lang')),
            ],
        ),
        migrations.CreateModel(
            name='Pood_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navbar.Lang')),
            ],
        ),
    ]
