# Generated by Django 2.2.9 on 2021-02-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode',
            name='pilt',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
