# Generated by Django 2.2.9 on 2021-02-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pood', '0002_toode_pilt'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode',
            name='pilt2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='toode',
            name='pilt3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='toode',
            name='pilt4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
