# Generated by Django 2.2.9 on 2021-02-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
        ('pood', '0004_pood_lang_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toode_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999)),
                ('lang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navbar.Lang')),
            ],
        ),
    ]
