# Generated by Django 2.2.9 on 2021-02-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pood', '0006_toode_lang_disclaimer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toode_lang',
            old_name='title',
            new_name='tagasi',
        ),
    ]
