# Generated by Django 2.2.9 on 2021-02-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pood', '0007_auto_20210204_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='pood_lang',
            name='bg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
