# Generated by Django 3.0 on 2021-02-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pood', '0008_pood_lang_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode_lang',
            name='bg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
